export enum AbsenceReasonEnum {
  SICK_LEAVE = "SICK_LEAVE",
  VACATION = "VACATION",
  PERSONAL_LEAVE = "PERSONAL_LEAVE",
  BUSINESS_TRIP = "BUSINESS_TRIP",
  TRAINING = "TRAINING",
  OTHER = "OTHER",
}
